In [1]:
import pandas as pd
import numpy as np

# **Table of Contents**

**Dataset Analysis**

1. Customers Dataset
2. Geolocation Dataset
3. Order Items Dataset
4. Order Payments Dataset
5. Order Reviews Dataset
6. Orders
7. Products Dataset
8. Sellers Dataset
9. Product Category Name Translation Dataset

**Data Joins**

1. Sales Trend
2. The States that Orders Most
3. The Top 10 Product Category
4. Average Delivery Time
5. Review Score Distribution
6. Multiple Reviews per Order
7. Delivery Time vs Review Score
8. Late Delivery vs Review Score

In [2]:
df_customers = pd.read_csv("data/olist_customers_dataset.csv")

df_geolocation = pd.read_csv("data/olist_geolocation_dataset.csv")

df_order_items = pd.read_csv("data/olist_order_items_dataset.csv")
df_order_payments = pd.read_csv("data/olist_order_payments_dataset.csv")
df_order_reviews = pd.read_csv("data/olist_order_reviews_dataset.csv")
df_orders = pd.read_csv("data/olist_orders_dataset.csv")

df_products = pd.read_csv("data/olist_products_dataset.csv")

df_sellers = pd.read_csv("data/olist_sellers_dataset.csv")

df_product_name_translation = pd.read_csv("data/product_category_name_translation.csv")

# **Dataset Analysis**

1. Customers Dataset
2. Geolocation Dataset
3. Order Items Dataset
4. Order Payments Dataset
5. Order Reviews Dataset
6. Orders
7. Products Dataset
8. Sellers Dataset
9. Product Category Name Translation Dataset

## Customers Dataset

In [3]:
df_customers.shape

(99441, 5)

In [4]:
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [5]:
df_customers.info()
df_customers.describe()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [6]:
df_customers.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Length: 99441, dtype: bool

In [7]:
df_customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [8]:
df_customers.isna()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99436,False,False,False,False,False
99437,False,False,False,False,False
99438,False,False,False,False,False
99439,False,False,False,False,False
99440,False,False,False,False,False

In [9]:
df_customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

## Geolocation Dataset

In [10]:
df_geolocation.shape

(1000163, 5)

In [11]:
df_geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [12]:
df_geolocation.info()
df_geolocation.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [13]:
df_geolocation.isna()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
1000158,False,False,False,False,False
1000159,False,False,False,False,False
1000160,False,False,False,False,False
1000161,False,False,False,False,False
1000162,False,False,False,False,False

In [14]:
df_geolocation.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [15]:
df_geolocation.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1000158    False
1000159     True
1000160     True
1000161    False
1000162     True
Length: 1000163, dtype: bool

In [16]:
df_geolocation.tail()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [17]:
df_geolocation.duplicated().sum()

np.int64(261831)

In [18]:
# 261,831 duplicate rows found, dropping them
df_geolocation = df_geolocation.drop_duplicates()

In [19]:
df_geolocation.duplicated().sum() # confirms 0

np.int64(0)

## Order Items Dataset

In [20]:
df_order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [21]:
df_order_items.shape

(112650, 7)

In [22]:
df_order_items.info()
df_order_items.describe()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [23]:
# shipping_limit_date was str, converting to datetime for time-based analysis
df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'], format='%Y-%m-%d %H:%M:%S')

In [24]:
df_order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [25]:
df_order_items.isna()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
112645,False,False,False,False,False,False,False
112646,False,False,False,False,False,False,False
112647,False,False,False,False,False,False,False
112648,False,False,False,False,False,False,False
112649,False,False,False,False,False,False,False

In [26]:
df_order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [27]:
df_order_items.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
112645    False
112646    False
112647    False
112648    False
112649    False
Length: 112650, dtype: bool

In [28]:
df_order_items.duplicated().sum()

np.int64(0)

## Order Payments Dataset

In [29]:
df_order_payments.shape

(103886, 5)

In [30]:
df_order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [31]:
df_order_payments.info()
df_order_payments.describe()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [32]:
df_order_payments.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [33]:
df_order_payments.duplicated().sum()

np.int64(0)

## Order Reviews Dataset

In [34]:
df_order_reviews.shape

(99224, 7)

In [35]:
df_order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [36]:
df_order_reviews.info()
df_order_reviews.describe()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [37]:
# review_creation_date and review_answer_timestamp were str, converting to datetime for time-based analysis
cols = ['review_creation_date', 'review_answer_timestamp']
df_order_reviews[cols] = df_order_reviews[cols].apply(pd.to_datetime, format='%Y-%m-%d %H:%M:%S')

In [38]:
df_order_reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [39]:
# review_comment_title (87656 missing) and review_comment_message (58247 missing)
# NaN means customer gave a score but left no written comment — expected, not an error
# left as NaN on purpose

In [40]:
df_order_reviews.duplicated().sum()

np.int64(0)

## Orders

In [41]:
df_orders.shape

(99441, 8)

In [42]:
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [43]:
df_orders.info()
df_orders.describe()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [44]:
# order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, and order_estimated_delivery_date were str, converting to datetime for time-based analysis
cols = ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
df_orders[cols] = df_orders[cols].apply(pd.to_datetime, format='%Y-%m-%d %H:%M:%S')

In [45]:
df_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [46]:
df_orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [47]:
# order_approved_at (160 missing), order_delivered_carrier_date (1783 missing),
# order_delivered_customer_date (2965 missing)
# NaN likely indicates orders not yet approved or delivered at time of data collection — expected, not an error
# left as NaN on purpose

In [48]:
df_orders.duplicated().sum()

np.int64(0)

## Products Dataset

In [49]:
df_products.shape

(32951, 9)

In [50]:
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [51]:
df_products.info()
df_products.describe()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [52]:
# One-liner summary
cols_to_check = [
    'product_name_lenght', 'product_description_lenght', 'product_photos_qty',
    'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm'
]
all_whole = {col: (df_products[col] % 1 == 0).all() for col in cols_to_check}
print(all_whole)

{'product_name_lenght': np.False_, 'product_description_lenght': np.False_, 'product_photos_qty': np.False_, 'product_weight_g': np.False_, 'product_length_cm': np.False_, 'product_height_cm': np.False_, 'product_width_cm': np.False_}

In [53]:
df_products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [54]:
for col in cols_to_check:
    n_nulls = df_products[col].isna().sum()
    has_decimals = (df_products[col].dropna() % 1 != 0).any()
    print(f"{col}: nulls={n_nulls}, has_decimals={has_decimals}")

product_name_lenght: nulls=610, has_decimals=False
product_description_lenght: nulls=610, has_decimals=False
product_photos_qty: nulls=610, has_decimals=False
product_weight_g: nulls=2, has_decimals=False
product_length_cm: nulls=2, has_decimals=False
product_height_cm: nulls=2, has_decimals=False
product_width_cm: nulls=2, has_decimals=False

In [55]:
df_products.duplicated().sum()

np.int64(0)

In [56]:
# actual rows where these are null
df_products[df_products['product_name_lenght'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [57]:
df_products[df_products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
# are the 610 nulls the same rows across all three columns?
mask = df_products[['product_name_lenght', 'product_description_lenght', 'product_photos_qty']].isna()
print(mask.sum())          # count per column
print(mask.all(axis=1).sum())  # rows where ALL THREE are null simultaneously

product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
dtype: int64
610

In [59]:
# fixing string "NaN"s
df_products.replace("NaN", np.nan, inplace=True)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [60]:
# Category → "unknown"
df_products['product_category_name'] = df_products['product_category_name'].fillna('unknown')

In [61]:
# Numeric → median
for col in ['product_name_lenght', 'product_description_lenght', 'product_photos_qty']:
    df_products[col] = df_products[col].fillna(df_products[col].median())

In [62]:
# Dimension columns (2 nulls) → drop
df_products.dropna(subset=['product_weight_g', 'product_length_cm',
                            'product_height_cm', 'product_width_cm'], inplace=True)

In [63]:
# Convert to int
int_cols = ['product_name_lenght', 'product_description_lenght', 'product_photos_qty']
df_products[int_cols] = df_products[int_cols].astype(int)

##### Last checks down below ↓ columns that need converted int, Nans replaced unknown, unnecessary Nans dropped, fixed typo on column names

In [64]:
df_products.info()

<class 'pandas.DataFrame'>
Index: 32949 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32949 non-null  str
 1   product_category_name       32949 non-null  str
 2   product_name_lenght         32949 non-null  int64
 3   product_description_lenght  32949 non-null  int64
 4   product_photos_qty          32949 non-null  int64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(4), int64(3), str(2)
memory usage: 2.5 MB

In [65]:
df_products.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [66]:
df_products[df_products["product_name_lenght"].isna()]

Empty DataFrame
Columns: [product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

In [67]:
df_products = df_products.rename(columns={'product_name_lenght': 'product_name_length', 'product_description_lenght': 'product_description_length'})

In [68]:
df_products.head()

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625.0,20.0,17.0,13.0

## Sellers Dataset

In [69]:
df_sellers.shape

(3095, 4)

In [70]:
df_sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [71]:
df_sellers.info()
df_sellers.describe()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [72]:
df_sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [73]:
df_sellers.duplicated().sum()

np.int64(0)

## Product Category Name Translation Dataset

In [74]:
df_product_name_translation.shape

(71, 2)

In [75]:
df_product_name_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [76]:
df_product_name_translation.info()
df_product_name_translation.describe()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [77]:
df_product_name_translation.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [78]:
df_product_name_translation.duplicated().sum()

np.int64(0)

# **Data Joins**

## Sales Trend - df_orders + df_order_items

In [79]:
df_sales_trend = df_orders.merge(df_order_items, on="order_id")

In [80]:
df_sales_trend.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

In [81]:
df_sales_trend["order_purchase_timestamp"] = pd.to_datetime(df_sales_trend["order_purchase_timestamp"])

In [82]:
df_sales_trend["order_month"] = df_sales_trend["order_purchase_timestamp"].dt.to_period("M")

In [83]:
# NOTE: includes all order statuses. Final analysis uses monthly_revenue_delivered_filtered below.
monthly_revenue = df_sales_trend.groupby("order_month")["price"].sum()

In [84]:
monthly_revenue

order_month
2016-09        267.36
2016-10      49507.66
2016-12         10.90
2017-01     120312.87
2017-02     247303.02
2017-03     374344.30
2017-04     359927.23
2017-05     506071.14
2017-06     433038.60
2017-07     498031.48
2017-08     573971.68
2017-09     624401.69
2017-10     664219.43
2017-11    1010271.37
2017-12     743914.17
2018-01     950030.36
2018-02     844178.71
2018-03     983213.44
2018-04     996647.75
2018-05     996517.68
2018-06     865124.31
2018-07     895507.22
2018-08     854686.33
2018-09        145.00
Freq: M, Name: price, dtype: float64

In [85]:
# 2016 data is excluded due to insufficient order volume
monthly_revenue_filtered = monthly_revenue["2017-01":]

In [86]:
monthly_revenue_filtered

order_month
2017-01     120312.87
2017-02     247303.02
2017-03     374344.30
2017-04     359927.23
2017-05     506071.14
2017-06     433038.60
2017-07     498031.48
2017-08     573971.68
2017-09     624401.69
2017-10     664219.43
2017-11    1010271.37
2017-12     743914.17
2018-01     950030.36
2018-02     844178.71
2018-03     983213.44
2018-04     996647.75
2018-05     996517.68
2018-06     865124.31
2018-07     895507.22
2018-08     854686.33
2018-09        145.00
Freq: M, Name: price, dtype: float64

In [87]:
df_sales_trend_delivered = df_sales_trend[df_sales_trend["order_status"] == "delivered"]

In [88]:
monthly_revenue_delivered = df_sales_trend_delivered.groupby("order_month")["price"].sum()

In [89]:
print(monthly_revenue_delivered.head(4))
monthly_revenue_delivered.tail(4)

order_month
2016-09       134.97
2016-10     40325.11
2016-12        10.90
2017-01    111798.36
Freq: M, Name: price, dtype: float64

order_month
2018-05    977544.69
2018-06    856077.86
2018-07    867953.46
2018-08    838576.64
Freq: M, Name: price, dtype: float64

In [90]:
# 2016 excluded (insufficient order volume); 2018-09 has no delivered orders
monthly_revenue_delivered_filtered = monthly_revenue_delivered["2017-01":"2018-08"]

In [91]:
len(monthly_revenue_delivered_filtered)

20

In [92]:
monthly_revenue_delivered_filtered

order_month
2017-01    111798.36
2017-02    234223.40
2017-03    359198.85
2017-04    340669.68
2017-05    489338.25
2017-06    421923.37
2017-07    481604.52
2017-08    554699.70
2017-09    607399.67
2017-10    648247.65
2017-11    987765.37
2017-12    726033.19
2018-01    924645.00
2018-02    826437.13
2018-03    953356.25
2018-04    973534.09
2018-05    977544.69
2018-06    856077.86
2018-07    867953.46
2018-08    838576.64
Freq: M, Name: price, dtype: float64

In [93]:
print(monthly_revenue.sum())
print(monthly_revenue_delivered.sum())

13591643.7
13221498.11

## The States that Orders Most - df_orders + df_customers

In [94]:
df_most_ordering_states = df_orders.merge(df_customers, on='customer_id')

In [95]:
df_most_ordering_states.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [96]:
df_most_ordering_states.groupby("customer_state")["order_id"].count().sort_values(ascending=False)

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: order_id, dtype: int64

In [97]:
df_most_ordering_states.groupby("customer_city")["order_id"].count().sort_values(ascending=False)

customer_city
sao paulo         15540
rio de janeiro     6882
belo horizonte     2773
brasilia           2131
curitiba           1521
                  ...
agisse                1
vieiras               1
bertopolis            1
abadiania             1
xexeu                 1
Name: order_id, Length: 4119, dtype: int64

In [98]:
df_result = df_most_ordering_states.groupby(["customer_state", "customer_city"])["order_id"].count().reset_index(name="order_count").sort_values(["customer_state", "order_count"], ascending=[True, False])

df_result.set_index(["customer_state", "customer_city"])

                                 order_count
customer_state customer_city
AC             rio branco                 70
               cruzeiro do sul             3
               senador guiomard            2
               xapuri                      2
               brasileia                   1
...                                      ...
TO             pium                        1
               praia norte                 1
               pugmil                      1
               sandolandia                 1
               silvanopolis                1

[4310 rows x 1 columns]

In [99]:
state_totals = df_result.groupby("customer_state")["order_count"].sum().reset_index(name="state_total")

df_result = df_result.merge(state_totals, on="customer_state").sort_values(["state_total", "order_count"], ascending=[False, False]).drop(columns="state_total")

df_result.set_index(["customer_state", "customer_city"])

                                      order_count
customer_state customer_city
SP             sao paulo                    15540
               campinas                      1444
               guarulhos                     1189
               sao bernardo do campo          938
               santo andre                    796
...                                           ...
AP             oiapoque                         1
               porto grande                     1
               vitoria do jari                  1
RR             boa vista                       45
               bonfim                           1

[4310 rows x 1 columns]

## The Top 10 Product Category - df_order_items + df_products + df_product_name_translation

In [100]:
df_merge = df_order_items.merge(df_products, on="product_id")

In [101]:
df_top10_product_category = df_merge.merge(df_product_name_translation, on="product_category_name", how="left")

In [102]:
print(df_order_items.shape[0])
df_merge.shape[0]

112650

112632

In [103]:
# 2 products were dropped during df_products cleaning (missing dimension data),
# so 18 order items (~0.02%) are excluded from the category analysis.
exists_in_products = df_order_items["product_id"].isin(df_products["product_id"])

not_in_products = ~exists_in_products

df_missing_items = df_order_items[not_in_products]

len(df_missing_items)
df_missing_items["product_id"].nunique()

2

In [104]:
print(df_merge.shape[0])
print(df_top10_product_category["product_category_name_english"].isna().sum())
df_top10_product_category.shape[0]

112632
1610

112632

In [105]:
# 1610 order items had no English category name (mostly 'unknown' from cleaning,
# plus a few categories missing in the translation table); filled with the original name.
df_missing_cat = df_top10_product_category[df_top10_product_category["product_category_name_english"].isna()]

In [106]:
df_missing_cat["product_category_name"].value_counts()

product_category_name
unknown                                          1586
portateis_cozinha_e_preparadores_de_alimentos      15
pc_gamer                                            9
Name: count, dtype: int64

In [107]:
df_top10_product_category["product_category_name_english"] = df_top10_product_category["product_category_name_english"].fillna(df_top10_product_category["product_category_name"])

In [108]:
df_top10_product_category["product_category_name_english"].isna().sum()
df_top10_product_category.shape[0]

112632

In [109]:
category_revenue = df_top10_product_category.groupby("product_category_name_english")["price"].sum()

In [110]:
# NOTE: includes all order statuses. Final analysis uses top10_categories_delivered below.
top10_categories = category_revenue.nlargest(10)
top10_categories

product_category_name_english
health_beauty            1258681.34
watches_gifts            1205005.68
bed_bath_table           1036988.68
sports_leisure            988048.97
computers_accessories     911954.32
furniture_decor           729762.49
cool_stuff                635290.85
housewares                632248.66
auto                      592720.11
garden_tools              485256.46
Name: price, dtype: float64

In [111]:
# NOTE: includes all order statuses. Final analysis uses top10_categories_delivered below.
top10_categories.sum() / category_revenue.sum()

np.float64(0.6237299329471512)

In [112]:
df_orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [113]:
# Only delivered orders are counted as revenue; canceled/unavailable and not-yet-delivered orders are excluded.
df_orders_delivered = df_orders[df_orders["order_status"]  == "delivered"]

In [114]:
print(df_orders_delivered.shape[0])
df_orders_delivered["order_status"].value_counts()

96478

order_status
delivered    96478
Name: count, dtype: int64

In [115]:
# Only delivered orders are counted as revenue; prices exclude freight_value.
df_cat_delivered = df_top10_product_category[df_top10_product_category["order_id"].isin(df_orders_delivered["order_id"])]
df_cat_delivered.shape[0]

110179

In [116]:
category_revenue_delivered = df_cat_delivered.groupby("product_category_name_english")["price"].sum()
top10_categories_delivered = category_revenue_delivered.nlargest(10)
top10_categories_delivered

product_category_name_english
health_beauty            1233131.72
watches_gifts            1166176.98
bed_bath_table           1023434.76
sports_leisure            954852.55
computers_accessories     888724.61
furniture_decor           711927.69
housewares                615628.69
cool_stuff                610204.10
auto                      578966.65
toys                      471286.48
Name: price, dtype: float64

In [117]:
category_revenue_delivered["garden_tools"]

np.float64(470495.27999999997)

In [118]:
print(category_revenue_delivered.sum())
monthly_revenue_delivered.sum()

13219001.110000001

np.float64(13221498.11)

In [119]:
top10_categories_delivered.sum() / category_revenue_delivered.sum()

np.float64(0.6244294982134244)

## Average Delivery Time - df_orders_delivered + order_purchase_timestamp + order_delivered_customer_date

In [120]:
# delivery_days = delivered date - purchase date, in fractional days
# 8 delivered orders have no order_delivered_customer_date -> NaN, left as is (excluded from mean/median)
# Distribution is right-skewed (mean 12.6 vs median 10.2; p99 = 46 days, max = 209 days)
# Outliers kept; median reported alongside the mean
df_orders_delivered["delivery_days"] = (df_orders_delivered["order_delivered_customer_date"] - df_orders_delivered["order_purchase_timestamp"]).dt.total_seconds() / 86400

In [121]:
df_orders_delivered.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days
count,96478,96464,96476,96470,96478,96470.000000
mean,2018-01-01 23:29:31.939913,2018-01-02 10:53:23.338012,2018-01-05 05:01:50.912330,2018-01-14 12:41:33.581683,2018-01-25 17:09:52.325711,12.558217
min,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-10-04 00:00:00,0.533414
25%,2017-09-14 09:00:23.250000,2017-09-14 14:48:54,2017-09-18 16:46:13.250000,2017-09-25 22:15:09.500000,2017-10-05 00:00:00,6.766204
50%,2018-01-20 19:45:45,2018-01-22 13:50:04,2018-01-24 16:13:47.500000,2018-02-02 19:32:21,2018-02-16 00:00:00,10.217477
75%,2018-05-05 18:54:47,2018-05-06 10:57:24.750000,2018-05-08 14:35:00,2018-05-15 22:54:48.500000,2018-05-28 00:00:00,15.720182
max,2018-08-29 15:00:37,2018-08-29 15:10:26,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,209.628611
std,NaN,NaN,NaN,NaN,NaN,9.546156

In [122]:
print(df_orders_delivered["delivery_days"].quantile([0.9, 0.95, 0.99]))
df_orders_delivered["delivery_days"].describe()

0.90    23.096377
0.95    29.274046
0.99    46.050262
Name: delivery_days, dtype: float64

count    96470.000000
mean        12.558217
std          9.546156
min          0.533414
25%          6.766204
50%         10.217477
75%         15.720182
max        209.628611
Name: delivery_days, dtype: float64

## Review Score Distribution - df_order_reviews

In [123]:
# Review scores (all reviews, all order statuses): 5 -> 57.8%, 4 -> 19.3%, 1 -> 11.5%, 3 -> 8.2%, 2 -> 3.2%
# Skewed toward 5, but 1-star is more common than 2- and 3-star (polarized extremes)
df_order_reviews["review_score"].value_counts(normalize=True).sort_index()

review_score
1    0.115133
2    0.031756
3    0.082430
4    0.192917
5    0.577763
Name: proportion, dtype: float64

In [124]:
# same distribution as percentages
df_order_reviews["review_score"].value_counts(normalize=True).sort_index()*100

review_score
1    11.513344
2     3.175643
3     8.242965
4    19.291704
5    57.776344
Name: proportion, dtype: float64

## Multiple Reviews per Order - df_order_reviews

In [125]:
print(df_order_reviews["review_id"].nunique())
df_order_reviews["order_id"].nunique()

98410

98673

In [126]:
df_order_reviews.duplicated(subset="review_id", keep=False).sum()

np.int64(1603)

In [127]:
df_order_reviews.groupby("order_id").size().value_counts().sort_index()

1    98126
2      543
3        4
Name: count, dtype: int64

In [128]:
(df_order_reviews.groupby("order_id")["review_score"].nunique()>1).sum()

np.int64(202)

In [129]:
# 547 orders had multiple reviews (202 with conflicting scores); kept the latest review per order
df_reviews_unique = (df_order_reviews.sort_values("review_answer_timestamp").drop_duplicates(subset="order_id", keep="last"))

In [130]:
print(df_reviews_unique.shape[0])
print(df_reviews_unique["order_id"].is_unique)
df_reviews_unique["review_score"].value_counts(normalize=True).sort_index()

98673
True

review_score
1    0.115158
2    0.031731
3    0.082424
4    0.192940
5    0.577747
Name: proportion, dtype: float64

In [131]:
df_order_reviews.duplicated(subset=["order_id", "review_answer_timestamp"], keep=False).sum()

np.int64(0)

## Delivery Time vs Review Score - df_orders_delivered + df_reviews_unique

In [132]:
# 646 delivered orders have no review; dropped by inner merge
df_delivery_reviews = df_orders_delivered.merge(df_reviews_unique, on="order_id", how="inner")

In [133]:
print(df_delivery_reviews.shape[0])
df_delivery_reviews["order_id"].is_unique

95832

True

In [134]:
df_delivery_reviews["delivery_days"].isna().sum()

np.int64(8)

In [135]:
df_delivery_reviews_dropped_nan = df_delivery_reviews.dropna(subset=["delivery_days"])
df_delivery_reviews_dropped_nan["delivery_days"].isna().sum()

np.int64(0)

In [136]:
# Delivered orders with a review, one review per order (latest kept).
# Median delivery time rises as score falls: 5-star 9.2 days -> 1-star 16.8 days.
# Mean-median gap also widens (1.4 -> 4.5 days): long delays concentrate in low scores.
# Association only; this does not show that delay causes the low score.
df_delivery_reviews.groupby("review_score")["delivery_days"].aggregate(["median", "mean", "count"])

                 median       mean  count
review_score
1             16.798287  21.321699   9351
2             13.226782  16.643326   2921
3             12.041644  14.256785   7916
4             10.787546  12.305974  18888
5              9.231429  10.680908  56748

## Late Delivery vs Review Score - df_delivery_reviews_dropped_nan

In [137]:
df_delivery_reviews_dropped_nan["order_estimated_delivery_date"].dt.normalize()

0       2017-10-18
1       2018-08-13
2       2018-09-04
3       2017-12-15
4       2018-02-26
           ...
95827   2017-03-28
95828   2018-03-02
95829   2017-09-27
95830   2018-02-15
95831   2018-04-03
Name: order_estimated_delivery_date, Length: 95824, dtype: datetime64[us]

In [138]:
# is_late = delivered date (normalized to day) > estimated delivery date
# 6.7% of delivered, reviewed orders arrived late (6381 of 95824)
# Mean review score: on time 4.29 (median 5), late 2.27 (median 1)
# Association only; does not show that lateness causes low scores
df_delivery_reviews_dropped_nan["is_late"] = (df_delivery_reviews_dropped_nan["order_delivered_customer_date"].dt.normalize() > df_delivery_reviews_dropped_nan["order_estimated_delivery_date"]
)

print(df_delivery_reviews_dropped_nan["is_late"].mean())
df_delivery_reviews_dropped_nan.groupby("is_late")["review_score"].aggregate(["median", "mean", "count"])

0.06659083319418935

         median      mean  count
is_late
False       5.0  4.290386  89443
True        1.0  2.270491   6381